package uk.nhs.nhsbsa.lis.rules.v1.model.application;

public enum SavingType {
	UNDEFINED,
	ACCOUNTS,
	PREMIUM_BONDS,
	INCOME_BONDS,
	CAPITAL_BONDS,
	SHARES,
	NATIONAL_SAVINGS_CERTIFICATES,
	UNIT_TRUSTS,
	PEPS,
	ISAS,
	OTHER_INVESTMENTS,
	OTHER_MONEY;
}
