package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;

global org.slf4j.Logger logger

// Not much of a rule to sum the values
rule "Total Outgoings"
	salience 40
when 
		Application : Application( applicant != null, myApplicant : applicant )
		$breakdown : AssessmentBreakdown($breakdown!=null)
	then
		$breakdown.setRunningPremiums(0.0);
		$breakdown.setTotalHousing(0.0);
		$breakdown.setRunningIncome(0.0);
		HelperFunctions.sumPremiums($breakdown);
		HelperFunctions.sumHousingCosts($breakdown);
		HelperFunctions.sumIncomeAndCapital($breakdown);
		HelperFunctions.sumRunningTotal($breakdown);
	end


// Assessment. The rules need to be clarified
rule "HC LIS Assessment"
	salience 20
when
	Application : Application( applicant != null, myApplicant : applicant )
	$breakdown : AssessmentBreakdown($breakdown!=null, hasPremiums() )
	
then
	Double lowerLimit=$breakdown.getPrescriptionPrice()/2;
	Double upperLimit=($breakdown.getPrescriptionPrice()/2)-$breakdown.getUpperLimitHC3Amount();
	if($breakdown.getRunningTotal() >= lowerLimit){
		// HC2
		logger.info("HC2");
	}
	else if($breakdown.getRunningTotal() < lowerLimit
			&& 
			$breakdown.getRunningTotal() >= upperLimit){
		// HC3
		logger.info("HC3");
	}
	else{
		// HC5
		logger.info("HC5");
	}
	 
end


	