package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
import uk.nhs.nhsbsa.lis.rules.v1.model.LisApplication;
import uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment.AssessmentCalculation;
import uk.nhs.nhsbsa.lis.rules.v1.model.*;
import uk.nhs.nhsbsa.lis.rules.v1.droolsengine.HelperFunctions;
import java.time.LocalDateTime;
import java.time.LocalDate;
import java.util.List;


rule "Total Outgoings"
	salience 40
when 
		lisApplication : LisApplication( applicant != null, myApplicant : applicant )
		assessmentCalc : AssessmentCalculation(assessmentCalc!=null)
	then
		HelperFunctions.logRule(assessmentCalc,"Total Outgoings");
		assessmentCalc.setRunningPremiums(0.0);
		HelperFunctions.sumPremiums(assessmentCalc);
		HelperFunctions.sumHousingCosts(assessmentCalc);
end


	