package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IRequireService requireService

rule "Breakdown Income"
	when 
	    $breakdown : Breakdown()
		$income : Income ( 
			receiving == true, 
			value.canConvert(), 
			owner.type in ( PersonType.MAIN_APPLICANT, PersonType.PARTNER ) )
    then
        $breakdown.addIncomeCapital($income);
end 

rule "Breakdown Benefits"
	when 
	    $breakdown : Breakdown()
		$benefit : Benefit ( 
			receiving == true, 
			value.canConvert(), 
			owner.type in ( PersonType.MAIN_APPLICANT, PersonType.PARTNER ) )
    then
        $breakdown.addIncomeCapital($benefit);
end 

