package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
import uk.nhs.nhsbsa.util.ObjectIndex;
import uk.nhs.nhsbsa.lis.rules.v1.model.*;
import uk.nhs.nhsbsa.lis.rules.v1.droolsengine.model.*;

global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IRequireService requireService

rule "Private Pension Rule"
    salience 80
when 
        lisApplication : LisApplication( applicant != null, myApplicant : applicant )
        $breakdown : AssessmentBreakdown()
    then
        logger.info("Private Pension Rule");
        
        List<String> privatePension = HelperFunctions.privatePensionBenefit(myApplicant);
        HelperFunctions.sumIncomeList($breakdown,privatePension,"Private Pension","Applicant");
end 

