package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IRequireService requireService

rule "Calculate Premiums"
	when
        Application : Application( applicant != null, myApplicant : applicant )
        $breakdown : AssessmentBreakdown()
    then
    	
end 

