package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IRequireService requireService

rule "Add Personal Allowance to Breakdown"
	when
        $breakdown : Breakdown()
        $allowance : PersonalAllowance()
    then
    	$breakdown.setPersonalAllowance($allowance);
end 

