package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory

rule "Default Application"
    when 
        $assessment : Assessment( )
        not Application( )
    then
        logger.info("Default Application");
        Application $application = factory.defaultApplication();
        modify ($assessment) { setApplication($application) };
        insert ($application);
end

rule "Default Applicant"
    when
        $application: Application ( applicant == null )
    then
        logger.info("Default Applicant");
        Person $applicant = factory.defaultPerson(PersonType.MAIN_APPLICANT);
        $application.setApplicant($applicant);
        insert ($applicant);
end

rule "Default Partner"
    when
        $application: Application ( partner == null, hasPartner == true )
    then
        logger.info("Default Partner");
        Person $partner = factory.defaultPerson(PersonType.PARTNER);
        $application.setPartner($partner);
        insert ($partner);
end
