package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IRequireService requireService

rule "Default Retirement Pension"
    when 
    	$index : ObjectIndex ()
        $person : Person ( type in ( PersonType.MAIN_APPLICANT, PersonType.PARTNER ) )
        not Income( owner == $person, type == IncomeType.OCC_PENSION )
    then
        Income $income = factory.defaultIncome(IncomeType.OCC_PENSION);
        $person.addIncome($income);
        $index.reindex($person);
        insert ($income);
end

