package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
import uk.nhs.nhsbsa.lis.rules.v1.model.*;
import uk.nhs.nhsbsa.lis.rules.v1.model.application.*;
import uk.nhs.nhsbsa.lis.rules.v1.model.flow.*;
import uk.nhs.nhsbsa.lis.rules.v1.model.outcome.*;
import uk.nhs.nhsbsa.lis.rules.v1.droolsengine.*;
import uk.nhs.nhsbsa.lis.rules.v1.droolsengine.model.*;
import uk.nhs.nhsbsa.util.*;
import java.time.*;
import java.util.*;
import java.math.*;

global org.slf4j.Logger logger
