package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory

rule "Age"
    when
        $application : Application()
        $person : Person( dob != null )
        exists ConsiderPerson( person == $person )
        not Age( person == $person )
    then
        insert ( new Age($application, $person) );
end

//TODO
rule "Oldest Applicant"
    when
    	$person : Person( type == PersonType.MAIN_APPLICANT )
    	$age : Age( person == $person)
        not OldestApplicant( )
    then
        insert ( new OldestApplicant($person, $age) );
end

rule "IsPensioner"
    when
        $person : Person()
        exists ConsiderPerson( person == $person )
        $age : Age( person == $person, value >= 60 )
    then
    	logger.info("IsPensioner");
        insert ( new IsPensioner($person) );
end