package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory

rule "Has Partner"
    when
        $application : Application ( hasPartner == true )
        $applicant : Person ( type == PersonType.MAIN_APPLICANT )
        $partner : Person ( type == PersonType.PARTNER )
    then
        insert ( new HasPartner($applicant, $partner) );
end

rule "Is Dependant"
    when
        $person : (Person( type in (PersonType.DEPENDANT)))
        $age : Age( person == $person, value < 16 )
    then
        logger.info("IsDependant");
        insert ( new IsDependant($person) );
end

rule "Is Non-dependant"
    when
        $person : (Person( type in (PersonType.DEPENDANT)))
        $age : Age( person == $person, value >= 16 )
    then
        logger.info("IsNonDependant");
        insert ( new IsNonDependant($person) );
end

