package uk.nhs.nhsbsa.lis.rules.v1.droolsengine.assessment;
 
import uk.nhs.nhsbsa.lis.rules.v1.model.*;
import uk.nhs.nhsbsa.lis.rules.v1.droolsengine.model.*;

global org.slf4j.Logger logger
global uk.nhs.nhsbsa.lis.rules.v1.droolsengine.service.IAssessmentFactoryService factory

rule "Age"
    when
        $application : LisApplication()
        $person : Person( dob != null )
        not Age( person == $person )
    then
        logger.info("Age");
        insert ( new Age($application, $person) );
end

rule "IsPensioner"
    when
        $person : (Person( type in (PersonType.MAIN_APPLICANT, PersonType.PARTNER )))
        $age : Age( person == $person, value >= 60 )
    then
    	logger.info("IsPensioner");
        insert ( new IsPensioner($person) );
end